### ISSUE TITLE
Validity message contains HTML

### ISSUE THREAD

**Issue by muan** [github/auto-check-element#17] opened 2019-07-18 17:18 UTC
In Chrome this message shows on submit:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1153134/61329738-12244c80-a7ec-11e9-84f8-7615ed282fbf.png">

In Firefox this message shows on hover:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1153134/61477772-035da700-a95e-11e9-8386-f59220faf6e4.png">

Cause:

https://github.com/github/auto-check-element/blob/d304e381c1c42b96cee5424da7a2c0a7a9871e2f/src/index.js#L131

We ask for HTML:

https://github.com/github/auto-check-element/blob/d304e381c1c42b96cee5424da7a2c0a7a9871e2f/src/index.js#L157

But the validity message should not contain HTML.

cc @github/web-systems

**Comment by koddsson** [comment] 2019-07-22 16:34
@muan Can you post reproduction steps? I tried reproducing this by:

- Opening github.com in a private browser profile
- Type `koddsson` in the username field
- See the validation error message

![image](https://user-images.githubusercontent.com/318208/61648200-e64f0e00-aca6-11e9-83e7-dd16d9a89ce2.png)

I don't see the custom validation error 😕

**Comment by muan** [comment] 2019-07-22 17:40
Try the signup page. On the homepage HTML validation seems to be disabled (invalid form can be submitted).

It is easiest to reproduce this in Firefox since the message shows up on hover.

![](https://cl.ly/ab4765b75455/Screen%252520Recording%2525202019-07-22%252520at%25252013.32.gif)

In Chrome this shows up when I enable the button and submit with invalid username:

![](https://cl.ly/ae32834d09de/Screen%252520Recording%2525202019-07-22%252520at%25252013.39.gif)

**Comment by koddsson** [comment] 2019-07-23 12:18
I think we did this originally to make the field invalid and when the field is invalid you can't submit the form and therefor the message would never be shown.

Since we can evidently can see the message we should do something about that. I think we've moved the actually showing the warning/error message so far away from the component that we can start returning text and handle that in the application code. That would mean that we'd show the correct validation message and show the warning/error in whatever HTML we'd want.

So we would start with returning text when requested in dotcom and then flip this component to request that.

**Comment by koddsson** [comment] 2019-07-23 12:39
If we do text it means we can't format it correctly though 🤔

**Comment by muan** [comment] 2019-07-23 15:05
> I think we've moved the actually showing the warning/error message so far away from the component that we can start returning text and handle that in the application code.

What is far away from the component? Isn't the response HTML still used and dependent on the same endpoint?

> If we do text it means we can't format it correctly though 🤔

I think we'll probably need to return both. Perhaps `auto-check` can has optional headers set for different responses it should retrieve set via an attribute?– 

- `text/plain`
- `text/html; fragment`
- `application/json` which has `{text, html}`

What do you think?

**Comment by koddsson** [comment] 2019-07-23 15:39
> > I think we've moved the actually showing the warning/error message so far away from the component that we can start returning text and handle that in the application code.
> 
> What is far away from the component? Isn't the response HTML still used and dependent on the same endpoint?

Sorry I wasn't being clear. I was trying to convey that the actual note that is displayed is now not part of the element anymore after we extracted it from the monolith. Not important 😄 




> > If we do text it means we can't format it correctly though 🤔
> 
> I think we'll probably need to return both. Perhaps `auto-check` can has optional headers set for different responses it should retrieve set via an attribute?–
> 
> * `text/plain`
> * `text/html; fragment`
> * `application/json` which has `{text, html}`
> 
> What do you think?

I like this, I was thinking it would be too complicated in the beginning but we can probably do this cleanly. I'm mostly leaning towards returning text and html via json.

**Comment by muan** [comment] 2019-07-23 16:04
> I was trying to convey that the actual note that is displayed is now not part of the element anymore after we extracted it from the monolith.

Aren't they still dependent on `event.detail.message`'s HTML response from `auto-check-error`?

> I like this, I was thinking it would be too complicated in the beginning but we can probably do this cleanly. I'm mostly leaning towards returning text and html via json.

👍 on not allowing just `text/html; fragment` since we need text for validity. I think it'd be good to support `text/plain` as a default for non-fancy use cases.

**Comment by dgraham** [comment] 2019-10-16 00:33
We added a validity message hook to the `auto-check-error` event in #37. The host application can provide the validation text based on the server response. Since the custom element is no longer responsible for reading the response body and setting the validation message, we can close this out.

**Closed by dgraham** 2019-10-16 00:33 UTC
Labels: bug
